
package assisted16;

public class except {
	S
	   public static void main(String args[]){
		try{
			System.out.println("Starting of try block");
			// I'm throwing the custom exception using throw
			throw new except("This is My error Message");
		}
		catch(expect exp){
			System.out.println("Catch Block") ;
			System.out.println(exp) ;
		}
	   }
}

	